// <auto-generated />
using System;
using ConsoleApp2205.Cofigs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Shortener1.Migrations
{
    [DbContext(typeof(SqlLightContext))]
    [Migration("20230608122406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("ConsoleApp2205.Entities.UrlMap", b =>
                {
                    b.Property<int>("urlMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created")
                        .HasColumnType("TEXT");

                    b.Property<string>("originalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("shortenedUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("usegCounter")
                        .HasColumnType("INTEGER");

                    b.HasKey("urlMapId");

                    b.ToTable("UrlMap");
                });
#pragma warning restore 612, 618
        }
    }
}
